import { expect, test } from 'bun:test';
import { join } from 'node:path';

import type { WebComponentArtifactFileSystemPort } from '../ports/outbound/WebComponentArtifactFileSystemPort';
import { materializeWebComponentArtifactAsync } from './materializeWebComponentArtifactAsync';

test('materializes the packaged tree-view web artifact without source ownership transfer', async () => {
  const packageRoot = '/package';
  const outputDirectory = '/consumer/src/generated/zora/tree-view';
  const writes = new Map<string, string>();
  const sources = new Map<string, string>([
    [join(packageRoot, 'web-dist', 'tree-view', 'TreeView.js'), 'export const TreeView = 1;\n'],
    [
      join(packageRoot, 'web-dist', 'tree-view', 'TreeView.d.ts'),
      'export declare const TreeView: unknown;\n',
    ],
  ]);

  const fileSystem: WebComponentArtifactFileSystemPort = {
    async ensureDirectoryAsync() {},
    async readTextFileAsync(path) {
      const source = sources.get(path);
      if (source === undefined) throw new Error(`Missing test source: ${path}`);
      return source;
    },
    async writeTextFileAsync(path, content) {
      writes.set(path, content);
    },
  };

  const result = await materializeWebComponentArtifactAsync(
    {
      component: 'tree-view',
      outputDirectory,
      packageRoot,
      packageVersion: '1.2.3',
    },
    fileSystem,
  );

  expect(result.platform).toBe('web');
  expect(result.createdFiles).toEqual([
    join(outputDirectory, 'TreeView.js'),
    join(outputDirectory, 'TreeView.d.ts'),
    join(outputDirectory, 'zora-artifact.json'),
  ]);
  expect(writes.get(join(outputDirectory, 'TreeView.js'))).toStartWith(
    '// Generated by @ankhorage/zora v1.2.3. Do not edit manually.',
  );
  expect(writes.get(join(outputDirectory, 'zora-artifact.json'))).toContain(
    '"owner": "@ankhorage/zora"',
  );
});

test('rejects unsupported web components explicitly', async () => {
  const fileSystem: WebComponentArtifactFileSystemPort = {
    async ensureDirectoryAsync() {},
    async readTextFileAsync() {
      return '';
    },
    async writeTextFileAsync() {},
  };

  await expect(
    materializeWebComponentArtifactAsync(
      {
        component: 'unknown',
        outputDirectory: '/consumer',
        packageRoot: '/package',
        packageVersion: '1.2.3',
      },
      fileSystem,
    ),
  ).rejects.toThrow('Unsupported ZORA web component: unknown');
});
