import { isRecord } from '@ankhorage/utility/object';

import type { WebComponentArtifactFileSystemPort } from '../ports/outbound/WebComponentArtifactFileSystemPort';

export interface MaterializeWebComponentArtifactInput {
  readonly component: string;
  readonly outputDirectory: string;
  readonly packageRoot: string;
  readonly packageVersion: string;
}

export interface MaterializeWebComponentArtifactResult {
  readonly component: string;
  readonly createdFiles: readonly string[];
  readonly outputDirectory: string;
  readonly platform: 'web';
}

/*** Materialize one replaceable web-only component artifact from the published ZORA catalog. */
export async function materializeWebComponentArtifactAsync(
  input: MaterializeWebComponentArtifactInput,
  fileSystem: WebComponentArtifactFileSystemPort,
): Promise<MaterializeWebComponentArtifactResult> {
  const artifact = await readWebArtifactDefinitionAsync(
    input.packageRoot,
    input.component,
    fileSystem,
  );
  const sourceDirectory = fileSystem.joinPath(input.packageRoot, 'web-dist', artifact.component);
  await fileSystem.ensureDirectoryAsync(input.outputDirectory);

  const createdFiles = await Promise.all(
    artifact.files.map(async (fileName) => {
      const sourcePath = fileSystem.joinPath(sourceDirectory, fileName);
      const targetPath = fileSystem.joinPath(input.outputDirectory, fileName);
      const source = await fileSystem.readTextFileAsync(sourcePath);
      await fileSystem.writeTextFileAsync(
        targetPath,
        createGeneratedSource(input.packageVersion, source),
      );
      return targetPath;
    }),
  );

  const metadataPath = fileSystem.joinPath(input.outputDirectory, 'zora-artifact.json');
  await fileSystem.writeTextFileAsync(
    metadataPath,
    `${JSON.stringify(
      {
        generated: true,
        owner: '@ankhorage/zora',
        version: input.packageVersion,
        component: input.component,
        platform: 'web',
      },
      null,
      2,
    )}\n`,
  );

  return {
    component: input.component,
    createdFiles: [...createdFiles, metadataPath],
    outputDirectory: input.outputDirectory,
    platform: 'web',
  };
}

interface WebArtifactDefinition {
  readonly component: string;
  readonly files: readonly string[];
}

interface WebArtifactManifestEntry {
  readonly component?: unknown;
  readonly files?: unknown;
}

/*** Resolve one requested component exclusively through the packaged web artifact catalog. */
async function readWebArtifactDefinitionAsync(
  packageRoot: string,
  component: string,
  fileSystem: WebComponentArtifactFileSystemPort,
): Promise<WebArtifactDefinition> {
  const manifestPath = fileSystem.joinPath(packageRoot, 'web-dist', 'manifest.json');
  const manifestSource = await readWebArtifactManifestSourceAsync(
    manifestPath,
    component,
    fileSystem,
  );

  let parsed: { readonly schemaVersion?: unknown; readonly artifacts?: unknown };
  try {
    parsed = JSON.parse(manifestSource) as typeof parsed;
  } catch {
    throw new Error('Invalid ZORA web artifact manifest.');
  }

  if (parsed.schemaVersion !== 1 || !Array.isArray(parsed.artifacts)) {
    throw new Error('Invalid ZORA web artifact manifest.');
  }

  const artifact = parsed.artifacts.find(
    (candidate): candidate is WebArtifactManifestEntry =>
      isRecord(candidate) && candidate.component === component,
  );
  if (artifact === undefined) {
    throw new Error(`Unsupported ZORA web component: ${component}`);
  }
  if (
    !Array.isArray(artifact.files) ||
    artifact.files.length === 0 ||
    !artifact.files.every((fileName) => typeof fileName === 'string' && fileName.length > 0)
  ) {
    throw new Error(`Invalid ZORA web artifact manifest entry: ${component}`);
  }

  return {
    component,
    files: artifact.files,
  };
}

/*** Read the packaged target catalog and translate a missing catalog into the CLI-facing error. */
async function readWebArtifactManifestSourceAsync(
  manifestPath: string,
  component: string,
  fileSystem: WebComponentArtifactFileSystemPort,
): Promise<string> {
  try {
    return await fileSystem.readTextFileAsync(manifestPath);
  } catch {
    throw new Error(`Unsupported ZORA web component: ${component}`);
  }
}

/*** Add a generated-file marker without changing the compiled artifact semantics. */
function createGeneratedSource(packageVersion: string, source: string): string {
  return `// Generated by @ankhorage/zora v${packageVersion}. Do not edit manually.\n${source}`;
}

