import { join } from 'node:path';

import type { WebComponentArtifactFileSystemPort } from '../ports/outbound/WebComponentArtifactFileSystemPort';

export interface MaterializeWebComponentArtifactInput {
  readonly component: string;
  readonly outputDirectory: string;
  readonly packageRoot: string;
  readonly packageVersion: string;
}

export interface MaterializeWebComponentArtifactResult {
  readonly component: string;
  readonly createdFiles: readonly string[];
  readonly outputDirectory: string;
  readonly platform: 'web';
}

/*** Materialize one replaceable web-only component artifact from the published ZORA build. */
export async function materializeWebComponentArtifactAsync(
  input: MaterializeWebComponentArtifactInput,
  fileSystem: WebComponentArtifactFileSystemPort,
): Promise<MaterializeWebComponentArtifactResult> {
  const artifact = resolveWebArtifact(input.component);
  const sourceDirectory = join(input.packageRoot, 'web-dist', artifact.directory);
  await fileSystem.ensureDirectoryAsync(input.outputDirectory);

  const createdFiles = await Promise.all(
    artifact.files.map(async (fileName) => {
      const sourcePath = join(sourceDirectory, fileName);
      const targetPath = join(input.outputDirectory, fileName);
      const source = await fileSystem.readTextFileAsync(sourcePath);
      await fileSystem.writeTextFileAsync(
        targetPath,
        createGeneratedSource(input.packageVersion, source),
      );
      return targetPath;
    }),
  );

  const metadataPath = join(input.outputDirectory, 'zora-artifact.json');
  await fileSystem.writeTextFileAsync(
    metadataPath,
    `${JSON.stringify(
      {
        generated: true,
        owner: '@ankhorage/zora',
        version: input.packageVersion,
        component: input.component,
        platform: 'web',
      },
      null,
      2,
    )}\n`,
  );

  return {
    component: input.component,
    createdFiles: [...createdFiles, metadataPath],
    outputDirectory: input.outputDirectory,
    platform: 'web',
  };
}

interface WebArtifactDefinition {
  readonly directory: string;
  readonly files: readonly string[];
}

/*** Resolve the canonical packaged web artifact for a requested component. */
function resolveWebArtifact(component: string): WebArtifactDefinition {
  if (component === 'tree-view') {
    return {
      directory: 'tree-view',
      files: ['TreeView.js', 'TreeView.d.ts'],
    };
  }

  throw new Error(`Unsupported ZORA web component: ${component}`);
}

/*** Add a generated-file marker without changing the compiled artifact semantics. */
function createGeneratedSource(packageVersion: string, source: string): string {
  return `// Generated by @ankhorage/zora v${packageVersion}. Do not edit manually.\n${source}`;
}
