import { expect, test } from 'bun:test';

import type { WebComponentArtifactFileSystemPort } from '../ports/outbound/WebComponentArtifactFileSystemPort';
import { materializeWebComponentArtifactAsync } from './materializeWebComponentArtifactAsync';

for (const artifact of [
  { component: 'tree-view', outputName: 'TreeView' },
  { component: 'graph-view', outputName: 'GraphView' },
] as const) {
  test(`materializes packaged ${artifact.component} without source ownership transfer`, async () => {
    const packageRoot = '/package';
    const outputDirectory = `/consumer/src/generated/zora/${artifact.component}`;
    const writes = new Map<string, string>();
    const sourceDirectory = `${packageRoot}/web-dist/${artifact.component}`;
    const sources = new Map<string, string>([
      [
        `${sourceDirectory}/artifact.json`,
        JSON.stringify({
          component: artifact.component,
          files: [`${artifact.outputName}.js`, `${artifact.outputName}.d.ts`],
        }),
      ],
      [`${sourceDirectory}/${artifact.outputName}.js`, 'export const component = 1;\n'],
      [
        `${sourceDirectory}/${artifact.outputName}.d.ts`,
        'export declare const component: unknown;\n',
      ],
    ]);
    const fileSystem = createFakeFileSystem(sources, writes);

    const result = await materializeWebComponentArtifactAsync(
      {
        component: artifact.component,
        outputDirectory,
        packageRoot,
        packageVersion: '1.2.3',
      },
      fileSystem,
    );

    expect(result.platform).toBe('web');
    expect(result.createdFiles).toEqual([
      `${outputDirectory}/${artifact.outputName}.js`,
      `${outputDirectory}/${artifact.outputName}.d.ts`,
      `${outputDirectory}/zora-artifact.json`,
    ]);
    expect(writes.get(`${outputDirectory}/${artifact.outputName}.js`)).toStartWith(
      '// Generated by @ankhorage/zora v1.2.3. Do not edit manually.',
    );
    expect(writes.get(`${outputDirectory}/zora-artifact.json`)).toContain(
      '"owner": "@ankhorage/zora"',
    );
  });
}

test('rejects unsupported web components explicitly', async () => {
  const fileSystem = createFakeFileSystem(new Map(), new Map());
  let caught: unknown;

  try {
    await materializeWebComponentArtifactAsync(
      {
        component: 'unknown',
        outputDirectory: '/consumer',
        packageRoot: '/package',
        packageVersion: '1.2.3',
      },
      fileSystem,
    );
  } catch (error) {
    caught = error;
  }

  expect(caught).toBeInstanceOf(Error);
  expect((caught as Error).message).toBe('Unsupported ZORA web component: unknown');
});

/*** Create a portable fake for the artifact filesystem port. */
function createFakeFileSystem(
  sources: ReadonlyMap<string, string>,
  writes: Map<string, string>,
): WebComponentArtifactFileSystemPort {
  return {
    joinPath(...parts) {
      return parts.join('/').replaceAll('//', '/');
    },
    ensureDirectoryAsync() {
      return Promise.resolve();
    },
    readTextFileAsync(path) {
      const source = sources.get(path);
      if (source === undefined) return Promise.reject(new Error(`Missing test source: ${path}`));
      return Promise.resolve(source);
    },
    writeTextFileAsync(path, content) {
      writes.set(path, content);
      return Promise.resolve();
    },
  };
}
