import type { WebComponentArtifactFileSystemPort } from '../ports/outbound/WebComponentArtifactFileSystemPort';

export interface MaterializeWebComponentArtifactInput {
  readonly component: string;
  readonly outputDirectory: string;
  readonly packageRoot: string;
  readonly packageVersion: string;
}

export interface MaterializeWebComponentArtifactResult {
  readonly component: string;
  readonly createdFiles: readonly string[];
  readonly outputDirectory: string;
  readonly platform: 'web';
}

/*** Materialize one replaceable web-only component artifact from the published ZORA build. */
export async function materializeWebComponentArtifactAsync(
  input: MaterializeWebComponentArtifactInput,
  fileSystem: WebComponentArtifactFileSystemPort,
): Promise<MaterializeWebComponentArtifactResult> {
  const sourceDirectory = fileSystem.joinPath(input.packageRoot, 'web-dist', input.component);
  const artifact = await readWebArtifactDefinitionAsync(
    sourceDirectory,
    input.component,
    fileSystem,
  );
  await fileSystem.ensureDirectoryAsync(input.outputDirectory);

  const createdFiles = await Promise.all(
    artifact.files.map(async (fileName) => {
      const sourcePath = fileSystem.joinPath(sourceDirectory, fileName);
      const targetPath = fileSystem.joinPath(input.outputDirectory, fileName);
      const source = await fileSystem.readTextFileAsync(sourcePath);
      await fileSystem.writeTextFileAsync(
        targetPath,
        createGeneratedSource(input.packageVersion, source),
      );
      return targetPath;
    }),
  );

  const metadataPath = fileSystem.joinPath(input.outputDirectory, 'zora-artifact.json');
  await fileSystem.writeTextFileAsync(
    metadataPath,
    `${JSON.stringify(
      {
        generated: true,
        owner: '@ankhorage/zora',
        version: input.packageVersion,
        component: input.component,
        platform: 'web',
      },
      null,
      2,
    )}\n`,
  );

  return {
    component: input.component,
    createdFiles: [...createdFiles, metadataPath],
    outputDirectory: input.outputDirectory,
    platform: 'web',
  };
}

interface WebArtifactDefinition {
  readonly component: string;
  readonly files: readonly string[];
}

/*** Read one packaged artifact manifest so new web components require no CLI branching. */
async function readWebArtifactDefinitionAsync(
  sourceDirectory: string,
  component: string,
  fileSystem: WebComponentArtifactFileSystemPort,
): Promise<WebArtifactDefinition> {
  const manifestPath = fileSystem.joinPath(sourceDirectory, 'artifact.json');
  const manifestSource = await readWebArtifactManifestSourceAsync(
    manifestPath,
    component,
    fileSystem,
  );
  const parsed = JSON.parse(manifestSource) as {
    readonly component?: unknown;
    readonly files?: unknown;
  };
  if (
    parsed.component !== component ||
    !Array.isArray(parsed.files) ||
    parsed.files.length === 0 ||
    !parsed.files.every((fileName) => typeof fileName === 'string' && fileName.length > 0)
  ) {
    throw new Error(`Invalid ZORA web artifact manifest: ${component}`);
  }

  return {
    component,
    files: parsed.files,
  };
}

/*** Read an artifact manifest and translate missing packages into the CLI-facing error. */
async function readWebArtifactManifestSourceAsync(
  manifestPath: string,
  component: string,
  fileSystem: WebComponentArtifactFileSystemPort,
): Promise<string> {
  try {
    return await fileSystem.readTextFileAsync(manifestPath);
  } catch {
    throw new Error(`Unsupported ZORA web component: ${component}`);
  }
}

/*** Add a generated-file marker without changing the compiled artifact semantics. */
function createGeneratedSource(packageVersion: string, source: string): string {
  return `// Generated by @ankhorage/zora v${packageVersion}. Do not edit manually.\n${source}`;
}
