sequenceDiagram
  participant participant_BottomSheet as BottomSheet
  participant participant_useBottomSheet as useBottomSheet
  participant_BottomSheet->>participant_useBottomSheet: useBottomSheet()
  participant_useBottomSheet-->>participant_BottomSheet: return
