sequenceDiagram
  participant participant_partitionListSections as partitionListSections
  participant participant_SectionList as SectionList
  participant_SectionList->>participant_partitionListSections: partitionListSections()
  participant_partitionListSections-->>participant_SectionList: return
