sequenceDiagram
  participant participant_useTheme as useTheme
  participant participant_useZoraTheme as useZoraTheme
  participant_useZoraTheme->>participant_useTheme: useTheme()
  participant_useTheme-->>participant_useZoraTheme: return
