sequenceDiagram
  participant participant_isEmail as isEmail
  participant participant_validateValue as validateValue
  participant_validateValue->>participant_isEmail: isEmail()
  participant_isEmail-->>participant_validateValue: return
