name: Renovate

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read
  pull-requests: read

jobs:
  changeset:
    if: >-
      github.actor == 'renovate[bot]' &&
      github.event.pull_request.head.repo.full_name == github.repository &&
      startsWith(github.event.pull_request.head.ref, 'renovate/')
    uses: ankhorage/renovate/.github/workflows/changeset.yml@f1e71e2812c1432499d975c2595d453dc9250065
    with:
      renovate_sync_client_id: ${{ vars.ANKHORAGE_RENOVATE_SYNC_CLIENT_ID }}
    secrets:
      renovate_sync_private_key: ${{ secrets.ANKHORAGE_RENOVATE_SYNC_PRIVATE_KEY }}
