name: Renovate

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  actions: write
  contents: write
  pull-requests: read

jobs:
  changeset:
    if: >-
      github.actor == 'renovate[bot]' &&
      github.event.pull_request.head.repo.full_name == github.repository &&
      startsWith(github.event.pull_request.head.ref, 'renovate/')
    uses: ankhorage/renovate/.github/workflows/changeset.yml@7d4a5104b94e763ca5be34919f4fcfbb12efd526
